<?php
/*
CMSimple version 2.4 - February 27. 2005 Small - simple - smart
© 1999-2005 Peter Andreas Harteg - peter@harteg.dk
IMPORTANT NOTICE: As covered by the AGPL Section 2(d), the "Powered by CMSimple"-link to cmsimple.dk must under no circumstances be removed from pages generated by this program (except in print facility). If you want to remove or hide this link from your pages, you must purchase CMSimple under a commercial license. This also applies testing purposes and setup at an intranet or internal network. This program is free software; you can redistribute it and/or modify it under the terms of the Affero General Public License (AGPL) as published by Affero, Inc. version 1. All files in the CMSimple distribution (except other language files than English and Danish) are covered by this license. Please be aware, that the AGPL in Section 2(d) requires, that any modified version of the program runned public (ie. on the Internet) must have an additional download facility for the modified version. This also applies to any modification of the template. Therefore you should purchase a commercial license, if you do not want the design of your internet site to fall under the AGPL license. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the AGPL for more details. A copy of the Affero General Public License is available at http://www.cmsimple.dk/?License:AGPL, if not, write to Affero, Inc., 510 Third Street, Suite 225, San Francisco, CA 94107 USA. This copyright note must under no circumstances be removed from this file and any distribution of code covered by this license. For further information about this license and how to purchase a commercial license, please see http://www.cmsimple.dk/?License.For downloads and information about installation, please see http://www.cmsimple.dk
*/

header('Content-type: text/html; charset=ISO-8859-15');

$uri 		= explode("/",$_SERVER['REQUEST_URI']);
$accName	= $uri[1];
$accLang	= $uri[2];

// LOAD ACC DATA
if(!include($_SERVER['DOCUMENT_ROOT'].'/data/acc/'.$accName.'.php')){ header('location: http://'.$_SERVER['HTTP_HOST'].'/'); exit; };

// LOAD SRV DATA
if(!include($_SERVER['DOCUMENT_ROOT'].'/data/srv/'.$accName.'.php')){ header('location: http://'.$_SERVER['HTTP_HOST'].'/'); exit; };

$cl=0; $e=''; $f=''; $hjs=''; $o=''; $onload=''; $sl=$uri['2']; $title='';

require('inc/router.php');

// LOAD INTRO
if(is_file($pth['site']['intro']) AND isset($uri['2']) AND $uri['2']==''){ require($pth['app']['inc'].'intro.php'); die; }

// LOAD DEFAULT SITE
if(isset($cf['site']['startLang']) AND $cf['site']['startLang']!=''){
	if(!isset($accLang) OR $accLang==''){ header("location: ./".$cf['site']['startLang']."/"); exit; }
} else die('ERRO: Não está definido o idioma inicial para este serviço.');

if(!is_file($pth['site']['content'])){ 
	if(is_file($pth['site']['root']."content.".$cf['site']['startLang'].".xml")){ header("location: ".$pth['site']['base'].$cf['site']['startLang']."/"); exit; }
	else { header('location: http://'.$_SERVER['HTTP_HOST'].'/'); exit; }
}
if(!include($pth['site']['locale'])){ header("location: ".$pth['site']['base'].$cf['site']['startLang']."/"); exit; }

require($pth['app']['inc'].'internalFunctions.php');
require($pth['app']['inc'].'master.php');

// Id Script Name
$sn=preg_replace('/([^\?]*)\?.*/','\1',$_SERVER['REQUEST_URI']);

if($_SERVER['QUERY_STRING']!=''){
	$rq=explode('&',$_SERVER['QUERY_STRING']);
	if (!strpos($rq[0], '='))$su = $rq[0];
	$v = count($rq);
	for($i = 0; $i < $v; $i++)
	if(!strpos($rq[$i], '='))$GLOBALS[$rq[$i]] = 'true';
} else $su = (isset($selected)) ? $selected : '';

$su = substr($su, 0, $cf['uri']['length']);

// READ FILE CONTENT.HTML
rfc();

// LOAD PAGE FUNCTIONS 
require($pth['app']['inc'].'pageFunctions.php');

// LOAD MODULES
clearstatcache();
$dir = opendir($pth['app']['module']);
while(($file=readdir($dir))==true ){ if(is_file($pth['app']['module'].$file)) require($pth['app']['module'].$file); }
if($dir==true)closedir($dir);

// LOAD CPANEL + LOGIN
$adm = (gc('status') == 'adm' && logincheck());

if(isset($login) AND $adm!=true)require($pth['app']['login']);
if(isset($newPassword) OR (isset($function) AND $function=='newPassword') OR isset($_GET['newPassword'])){ $f='newPassword'; include('inc/newPassword.php'); }

if(isset($adm) AND $adm==TRUE){
	if (isset($edit))setcookie('mode', 'edit');
	if (isset($normal))setcookie('mode', '');
	if (gc('mode') == 'edit' && !isset($normal))$edit = true;
} else {
	if (gc('status') != '')setcookie('status', '');
	if (gc('passwd') != '')setcookie('passwd', '');
	if (gc('mode') == 'edit')setcookie('mode', '');
}

if(isset($adm) AND $adm==true) require('admin/admin.php');

if($s==-1 AND !$f AND $o=='' AND (!isset($_GET['download']) OR $_GET['download']=='')){ 
	$tmp=explode('/',$_SERVER['REQUEST_URI']);
	if($su!='' OR (isset($tmp[3]) AND $tmp[3]!='' AND $tmp[3]!='index.php')){ header('Status: 404 Not Found'); $e=$txt['error']['404']; }
	else { $s=0; $hs=0; };
}

// LOAD CODIGOV
require($pth['app']['inc'].'codigov.php');

foreach(array('content','config','log') as $i)chkfile($i,((isset($login) OR isset($setup)) AND isset($adm)));

if($_GET['download']!='')download($pth['site']['archive'].basename($_GET['download']));
if($e) 			$o=msgBox($e).$o;
if($title=='')	{ if($s>-1)$title=$h[$s]; else if($f!='')$title=ucfirst($f); }
if($retrieve)	{ print '<html><head>'.head().'</head><body>'.$c[$s].'</body></html>'; exit; }
if($print)		{ print '<html><head>'.head().'</head><body class="print"'.onload().'>'.content().'</body></html>'; exit; }

if(!@include($pth['site']['structure'])) print '<html><head><title></title></head><body>'.$o.'</body></html>';

?>